openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: PhoneBook with your contacts
tags:
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-tbci.onrender.com
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
